"""added timestamps to posts

Revision ID: 0386288935ae
Revises: 
Create Date: 2025-05-03 16:19:08.374971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0386288935ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=True))

    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
