"""changed table names

Revision ID: 1eee36becf78
Revises: 6959955fd9bf
Create Date: 2025-05-03 02:25:39.009644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eee36becf78'
down_revision = '6959955fd9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], )
    )
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('video_id', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_ibfk_1'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='likes_ibfk_2'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('video_likes')
    # ### end Alembic commands ###
