"""changed user

Revision ID: 534e30f6d41e
Revises: 
Create Date: 2025-05-08 23:41:20.537607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534e30f6d41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_hashtags',
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.Column('hashtag_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], )
    )
    op.create_table('edit_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('comment_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.Column('comment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('gender')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('gender',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.drop_table('comment_likes')
    op.drop_table('edit_likes')
    op.drop_table('edit_hashtags')
    # ### end Alembic commands ###
