"""added comments likes

Revision ID: 74c8df5cb4e5
Revises: 1eee36becf78
Create Date: 2025-05-03 02:34:46.325078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c8df5cb4e5'
down_revision = '1eee36becf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('comment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
