"""added software id

Revision ID: 765bdcd0526e
Revises: c3db4e442e36
Create Date: 2025-05-09 03:39:38.092102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765bdcd0526e'
down_revision = 'c3db4e442e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
