"""added more user details

Revision ID: a182b0383f5a
Revises: 
Create Date: 2025-05-06 22:21:52.180125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182b0383f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'software', ['software_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('pronouns')

    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
