"""software table

Revision ID: aa1f9dac5b0b
Revises: 0386288935ae
Create Date: 2025-05-03 16:46:43.927371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1f9dac5b0b'
down_revision = '0386288935ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.String(length=32), nullable=False))
        batch_op.create_foreign_key(None, 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('software_id')

    op.drop_table('software')
    # ### end Alembic commands ###
