"""added a pfp field

Revision ID: bd4fc3a990b0
Revises: d115f4feedba
Create Date: 2025-05-07 05:24:20.596309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4fc3a990b0'
down_revision = 'd115f4feedba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasPfp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hasPfp')

    # ### end Alembic commands ###
