"""added gender enum

Revision ID: bd5281ef1e2c
Revises: 534e30f6d41e
Create Date: 2025-05-08 23:50:04.018384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models.enums import UserGender

# revision identifiers, used by Alembic.
revision = 'bd5281ef1e2c'
down_revision = '534e30f6d41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_pfp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PREFER', 'OTHER', name='usergender'), nullable=True))

        batch_op.drop_column('hasPfp')

    op.execute(f"UPDATE user SET gender = 'PREFER'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasPfp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('has_pfp')

    # ### end Alembic commands ###
