"""added age

Revision ID: c3db4e442e36
Revises: bd5281ef1e2c
Create Date: 2025-05-09 03:34:43.847222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3db4e442e36'
down_revision = 'bd5281ef1e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE', 'PREFER', 'OTHER'),
               nullable=False)
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE', 'PREFER', 'OTHER'),
               nullable=True)
        batch_op.drop_column('age')

    # ### end Alembic commands ###
