"""changed edit timestamp to created_at

Revision ID: efb0c1fa6696
Revises: a182b0383f5a
Create Date: 2025-05-06 22:25:47.811047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efb0c1fa6696'
down_revision = 'a182b0383f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
