"""removed some nullables

Revision ID: a93aef95df44
Revises: c08c031b2620
Create Date: 2025-05-15 01:56:48.917562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a93aef95df44'
down_revision = 'c08c031b2620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('pronouns',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE', 'PREFER', 'OTHER'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('MALE', 'FEMALE', 'PREFER', 'OTHER'),
               nullable=False)
        batch_op.alter_column('pronouns',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
