"""readded all the tables

Revision ID: c08c031b2620
Revises: 
Create Date: 2025-05-15 01:45:29.400015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08c031b2620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('pronouns', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PREFER', 'OTHER', name='usergender'), nullable=False),
    sa.Column('software_id', sa.String(length=32), nullable=True),
    sa.Column('picture_url', sa.Text(), nullable=True),
    sa.Column('sub', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('sub'),
    sa.UniqueConstraint('username')
    )
    op.create_table('edit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('software_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.String(length=32), nullable=False),
    sa.Column('followed_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('edit_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_id'], ['comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('edit_hashtags',
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.Column('hashtag_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], )
    )
    op.create_table('edit_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('comment_likes',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('edit_id', sa.String(length=32), nullable=True),
    sa.Column('comment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    op.drop_table('edit_likes')
    op.drop_table('edit_hashtags')
    op.drop_table('comment')
    op.drop_table('followers')
    op.drop_table('edit')
    op.drop_table('user')
    op.drop_table('software')
    op.drop_table('hashtag')
    # ### end Alembic commands ###
